---
layout: page
title: "대한민국 제21대 국회의원 선거"
subtitle: "제20대 선거구 통계청행정동경계"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

# 0. 환경설정 -----
library(tidyverse)
library(rvest)
library(httr)

```

# 선거구와 행정동 경계 [^map-district] {#district-map}

[^map-district]: [서울대에서 GIS하기 (2016-12-02), "제20대 국회의원 선거구 전국지도"](https://snugis.tistory.com/127)


```{r district-cnt}
library(tidyverse)
library(sf)

## 제20대 선거구 데이터
raw_sf <- st_read("data/shapefile/election_district_20/election_district_20.shp")

district_sf <- raw_sf %>% 
  group_by(province, SGG_NM) %>% 
  summarize(cnt = n())

district_sf
```

```{r district-viz}
district_sf %>% 
  ggplot(aes(fill=cnt)) +
    geom_sf()
```

