---
layout: page
title: "제21대 국회의원 선거"
subtitle: "성남시 인구변화"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')


```

# 성남시 인구통계 데이터 {#sungnam-population-dataset}

[성남시 통계 홈페이지](http://stat.seongnam.go.kr/)를 방문하면 "성남통계" &rarr; "월별 인구 및 세대 통계"  게시판을 통해 월별 성남시 인구 및 세대현황에 대한 상세 현황을 받을 수 있다. [성남시 월별 인구 및 세대 통계](http://stat.seongnam.go.kr/sn_stat/sub17.asp?id=wholesale_retail_census) 웹사이트에서 직접 게시판을 통해 다운로드 받는 것이 가능하다.


```{r sungnam-population-dataset}
library(tidyverse)
library(readxl)

pop_sujung_201703 <- read_excel("data/2017.3월 인구현황.xlsx", sheet="연령별인구_수정", skip=6)

pop_sujung_201703 <- pop_sujung_201703 %>% 
  select(which(str_detect(colnames(pop_sujung_201703), "연    령|동|\\.\\.2\\b"))) %>% 
  rename(`남녀` = "..2", 
         `연령` = "연    령") %>% 
  
  filter(str_detect(`남녀`, "남|영"))




```




