---
layout: page
title: "재보선 2019 선거"
subtitle: "총선, 대선, 지선 3대 선거 데이터 분석"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: false
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

Sys.setenv(RSTUDIO_PANDOC="C:/Users/victor/AppData/Local/Pandoc")

library(tidyverse)

sido_tbl <- tribble(
  ~"sido", ~"시도명",
  "강원",	"강원도",
  "경기",	"경기도",
  "경남",	"경상남도",
  "경북",	"경상북도",
  "광주",	"광주광역시",
  "대구",	"대구광역시",
  "대전",	"대전광역시",
  "부산",	"부산광역시",
  "서울",	"서울특별시",
  "세종",	"세종특별자치시",
  "울산",	"울산광역시",
  "인천",	"인천광역시",
  "전남",	"전라남도",
  "전북",	"전라북도",
  "제주",	"제주특별자치도",
  "충남",	"충청남도",
  "충북",	"충청북도"  )

```

# 3대 선거 - 전체 득표수 {#major-election}

```{r major-election}
library(krvotes)
library(tidyverse)

# 3대 선거 데이터 정리 ------
## 총선 (2016)
congress_df <- congress_2018

congress_vote <- congress_df %>% 
  mutate(`자한당` = map_dbl(data_clean, ~select(., contains("새누리당")) %>% unlist %>% sum),
         `민주당` = map_dbl(data_clean, ~select(., contains("민주당")) %>% unlist %>% sum),
         `바미당` = map_dbl(data_clean, ~select(., contains("국민")) %>% unlist %>% sum),
         `정의당` = map_dbl(data_clean, ~select(., contains("정의")) %>% unlist %>% sum)) %>% 
  summarise(`민주당` = sum(`민주당`),
            `자한당` = sum(`자한당`),
            `바미당` = sum(`바미당`),
            `정의당` = sum(`정의당`)) %>% 
  mutate(`선거` = "2016_총선")

## 대선 (2017)
president_df <- president

president_vote <- president_df %>% 
  summarise(`민주당` = sum(`문재인`),
            `자한당` = sum(`홍준표`),
            `바미당` = sum(`안철수`, `유승민`),
            `정의당` = sum(`심상정`)) %>% 
  mutate(`선거` = "2017_대선")

## 지선 (2018)
local_df <- local_2018

local_vote <- local_df %>% 
    mutate(`자한당` = map_dbl(data_clean, ~select(., contains("자유한국")) %>% unlist %>% sum),
           `민주당` = map_dbl(data_clean, ~select(., contains("민주당")) %>% unlist %>% sum),
           `바미당` = map_dbl(data_clean, ~select(., contains("바른")) %>% unlist %>% sum),
           `정의당` = map_dbl(data_clean, ~select(., contains("정의")) %>% unlist %>% sum)) %>% 
  summarise(`민주당` = sum(`민주당`),
            `자한당` = sum(`자한당`),
            `바미당` = sum(`바미당`),
            `정의당` = sum(`정의당`)) %>% 
  mutate(`선거` = "2018_지선")
```



```{r major-election-viz}
# 데이터 분석 ------
library(extrafont)
loadfonts()

three_df <- bind_rows(congress_vote, president_vote) %>% 
  bind_rows(local_vote)

three_df %>% 
  gather(`정당`, `득표수`, -`선거`) %>% 
  mutate(`득표수` = `득표수`/10^4) %>% 
  mutate(`정당` = factor(`정당`, levels=c("민주당", "자한당", "바미당", "정의당"))) %>% 
  ggplot(aes(x=`선거`, y=`득표수`, color=`정당`, group=`정당`)) +
    geom_point(size=2) +
    geom_line() +
    scale_color_manual(values = c("blue", "red", "cyan", "yellow")) +
    theme_bw(base_family = "NanumGothic") +
    labs(x="", y="정당득표수", title="총선, 대선, 지선 정당별 득표수",
         subtitle="단위: 만명") +
    theme(legend.position = "top") +
    scale_y_continuous(labels = scales::comma)

three_df %>% 
  select(`선거`, everything()) %>% 
  DT::datatable() %>% 
    DT::formatRound(c(2:5), digits=0)

```

# 3대 선거 - 시도별 득표수 {#major-election-province}

```{r major-province, eval=FALSE}
# 3대 선거 데이터 정리 ------
## 총선 (2016)
congress_df <- congress_2018

congress_vote <- congress_df %>% 
  mutate(`자한당` = map_dbl(data_clean, ~select(., contains("새누리당")) %>% unlist %>% sum),
         `민주당` = map_dbl(data_clean, ~select(., contains("민주당")) %>% unlist %>% sum),
         `바미당` = map_dbl(data_clean, ~select(., contains("국민")) %>% unlist %>% sum),
         `정의당` = map_dbl(data_clean, ~select(., contains("정의")) %>% unlist %>% sum)) %>% 
  group_by(sido) %>% 
  summarise(`민주당` = sum(`민주당`),
            `자한당` = sum(`자한당`),
            `바미당` = sum(`바미당`),
            `정의당` = sum(`정의당`)) %>% 
  mutate(`선거` = "2016_총선")

## 대선 (2017)
president_df <- president

president_vote <- president_df %>% 
  group_by(`시도명`) %>% 
  summarise(`민주당` = sum(`문재인`),
            `자한당` = sum(`홍준표`),
            `바미당` = sum(`안철수`, `유승민`),
            `정의당` = sum(`심상정`)) %>% 
  mutate(`선거` = "2017_대선")

## 지선 (2018)
local_df <- local_2018

local_vote <- local_df %>% 
    mutate(`자한당` = map_dbl(data_clean, ~select(., contains("자유한국")) %>% unlist %>% sum),
           `민주당` = map_dbl(data_clean, ~select(., contains("민주당")) %>% unlist %>% sum),
           `바미당` = map_dbl(data_clean, ~select(., contains("바른")) %>% unlist %>% sum),
           `정의당` = map_dbl(data_clean, ~select(., contains("정의")) %>% unlist %>% sum)) %>%
  group_by(`선거구명`) %>% 
  summarise(`민주당` = sum(`민주당`),
            `자한당` = sum(`자한당`),
            `바미당` = sum(`바미당`),
            `정의당` = sum(`정의당`)) %>% 
  mutate(`선거` = "2018_지선")
```

```{r major-province-viz,fig.width=12, fig.height=8, eval=FALSE}
local_vote <- local_vote %>% 
  rename(`시도명` = `선거구명`) 

# president_vote

congress_vote <- congress_vote %>% 
  left_join(sido_tbl) %>% 
  select(`시도명`, everything()) %>% 
  select(-sido)

vote_sido_df <- bind_rows(local_vote, president_vote)  %>% 
  bind_rows(congress_vote)

vote_sido_df %>% 
  gather(`정당`, `득표수`, -`선거`, -`시도명`) %>% 
  mutate(`득표수` = `득표수`/10^4) %>% 
  mutate(`정당` = factor(`정당`, levels=c("민주당", "자한당", "바미당", "정의당"))) %>% 
  ggplot(aes(x=`선거`, y=`득표수`, color=`정당`, group=`정당`)) +
    geom_point(size=2) +
    geom_line() +
    scale_color_manual(values = c("blue", "red", "cyan", "yellow")) +
    theme_bw(base_family = "NanumGothic") +
    labs(x="", y="정당득표수", title="총선, 대선, 지선 정당별 득표수",
         subtitle="단위: 만명") +
    theme(legend.position = "top") +
    scale_y_continuous(labels = scales::comma) +
    facet_wrap(~`시도명`, scale="free")

vote_sido_df %>% 
  select(`선거`, everything()) %>% 
  DT::datatable() %>% 
    DT::formatRound(c(3:6), digits=0)


```

