---
layout: page
title: "제21대 국회의원 선거"
subtitle: "성남시 - 시청과 3구청"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# 성남시 - 시청과 구청 {#sungnam-map}

전국 관공서 위치중 성남시 관공서 위치만 추려 `sungnam_df` 데이터프레임으로 생성시킨다.
시군구 행정지도에서 성남시만 추출하여 지도도 별도로 준비한다.

## 성남시청과 3구청 {#sungnam-map-data}

먼저 성남시 기초 주소 및 위치정보를 데이터프레임으로 준비한다.

```{r local-gov-sungnam-lonlat}
library(tidyverse)
library(sf)

## 성남시 관공서 위치
local_lonlat_df <- read_rds("data/local_lonlat_df.rds")

sungnam_df <- local_lonlat_df %>% 
  filter(str_detect(`기관명`, "성남"))

sungnam_df %>% 
  mutate(`홈페이지` = paste0("<a href=", `홈페이지`, ">", `홈페이지`, "</a>")) %>% 
  DT::datatable(escape=FALSE) %>% 
  DT::formatRound(c("lon", "lat"), digits=2)
```

## 성남시청과 3구청 {#sungnam-map-data}

행정지도에서 성남시와 3구만 추려 `sungnam_sf` 데이터프레임으로 만들어낸다.

```{r local-gov-sungnam-sf}
## 성남시 시군구 지도
sigungu_sf <- st_read("data/shapefile/SIG_201902/TL_SCCO_SIG.shp")

### 인코딩 변경
sigungu_sf$SIG_KOR_NM <- iconv(sigungu_sf$SIG_KOR_NM, from = "CP949", to = "UTF-8", sub = NA, mark = TRUE, toRaw = FALSE)

### 좌표계 변경: 웹 메르카도(web mercator)
sigungu_sf <- st_transform(sigungu_sf, "+proj=longlat +datum=WGS84")


### 성남시
sungnam_sf <- sigungu_sf %>% 
  filter(str_detect(SIG_KOR_NM, "성남"))

## 시각화 
sungnam_sf %>% 
  select(SIG_KOR_NM) %>% 
  plot()
```


# 성남시청과 3구청 시각화 {#sungnam-map-leaflet}

앞서 작업한 내용을 성남시청과 성남 3구청(수정구, 분당구, 중원구) 시각화하여 지도위에 올려본다.

```{r local-gov-sungnam-sf-leaflet}
library(leaflet)

## 라벨
pop_labels <- sprintf(
  "<strong>%s</strong><br/>",
  sungnam_sf$SIG_KOR_NM) %>% lapply(htmltools::HTML)

leaflet() %>%
  addTiles() %>% 
  addProviderTiles(providers$OpenStreetMap) %>% 
  addMarkers(data=sungnam_df, lng=~lon, lat=~lat, clusterOptions = markerClusterOptions(),
                   popup = ~ as.character(paste0("<strong>", paste0("지방자치단체: ",`기관명`), "</strong><br>",
                                                 "-----------------------------------------------------------<br>",
                                                 "&middot; 주소: ", `주소`, "<br>",
                                                 "&middot; 전화번호: ", `전화번호`, "<br>",
                                                 "&middot; 홈페이지: ", `홈페이지`, "<br>"))) %>% 
  addPolygons(data=sungnam_sf, opacity = 1.0, fillOpacity = 0.5,
              weight = 1,
              highlightOptions = highlightOptions(color = "black", weight = 3,  bringToFront = TRUE),
              label = pop_labels,
              labelOptions = labelOptions(
              style = list("font-weight" = "normal", padding = "3px 8px"),
              textsize = "15px",
              direction = "auto"))
```



