---
layout: page
title: "제21대 국회의원 선거"
subtitle: "성남시 분당구"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')


```

# 총선 &rarr; 대선 &rarr; 지선 {#major-election}

`krvotes` 팩키지에서 준비된 총선, 대선, 지선 데이터를 바탕으로 분당구 득표 데이터를 비교가능하도록 정당별로 준비시킨다.

- 분당을의 경우 무소속 임태희 후보는 자한당으로 넣어 데이터를 준비한다.
- 대선 유승민과 안철수는 합쳐서 바른미래당으로 준비한다.

```{r major-election-vote}
library(tidyverse)
library(krvotes)

# 총선 2016 -----
총선_df <- congress_2018 %>% 
  filter(str_detect(`precinct`, "분당")) %>% 
  unnest(data_clean) %>% 
  group_by(`읍면동명`) %>% 
  summarise(`민주당` = sum(`더불어민주당 김병관`, `더불어민주당 김병욱`, na.rm=TRUE),
         `자한당` = sum(`새누리당 권혁세`, `새누리당 전하진`, `무소속 임태희`, na.rm=TRUE),
         `바미당` = sum(`국민의당 염오봉`, `국민의당 윤은숙`, na.rm=TRUE)) %>% 
  mutate(`선거` = "2016총선")

# 대선 2017 -----
대선_df <- president %>% 
  tbl_df %>% 
  filter(str_detect(`구시군명`, "분당")) %>% 
  group_by(`읍면동명`) %>% 
  summarise(`민주당` = sum(`문재인`),
            `자한당` = sum(`홍준표`),
            `바미당` = sum(`안철수`, `유승민`),
            `정의당` = sum(`심상정`)) %>% 
  mutate(`선거` = "2017대선")


# 지선 2018 -----
지선_df <- local_2018 %>% 
  filter(str_detect(`시도명`, "경기")) %>% 
  select(-시도명) %>% 
  unnest(data_clean) %>% 
  filter(str_detect(`구시군명`, "분당")) %>% 
  group_by(`읍면동명`) %>% 
  summarise(`민주당` = sum(`더불어민주당 이재명`),
            `자한당` = sum(`자유한국당 남경필`),
            `바미당` = sum(`바른미래당 김영환`),
            `정의당` = sum(`정의당 이홍우`)) %>% 
  mutate(`선거` = "2018지선")

분당_df <- bind_rows(`총선_df`, `대선_df`) %>% 
  bind_rows(`지선_df`) %>% 
  filter(!str_detect(읍면동명, "잘못")) %>% 
  mutate(정의당 = ifelse(is.na(`정의당`), 0, `정의당`)) %>% 
  select(선거, everything())
```


# 정당별 득표 테이블 {#major-election-table}

```{r major-election-vote-table}
분당_df %>% 
  arrange(desc(`민주당`)) %>% 
  DT::datatable() %>% 
    DT::formatRound(3:6, digits=0)
```

# 정당별 득표 시각화 {#major-election-table}

```{r major-election-vote-viz, fig.width=12, fig.height=10}
`분당_df` %>% 
  filter(!str_detect(`읍면동명`, "재외투표|국외부재자투표|거소")) %>% 
  gather(`정당`, `득표수`, -`선거`, -`읍면동명`) %>% 
  mutate(`정당` = factor(`정당`, levels =c("민주당", "자한당", "바미당", "정의당"))) %>% 
  mutate(`선거` = factor(`선거`, levels =c("2018지선", "2017대선", "2016총선"))) %>% 
    ggplot(aes(x=fct_reorder(`정당`, `득표수`), y=`득표수`, fill=`선거`)) +
    geom_col(position = "dodge") +
    coord_flip() +
    facet_wrap(~`읍면동명`) +
    scale_fill_manual(values=c("black", "gray90", "gray70" )) +
    theme_minimal() +
    scale_y_continuous(labels = scales::comma) +
    labs(x="") +
    theme(legend.position = "top")
```


