---
layout: page
title: "대한민국 제21대 국회의원 선거"
subtitle: "선거구별 지지율"
author:
    name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(tidyverse)
library(rvest)

```

# 데이터 {#precinct-approval}

## 특정 여론조사 {#precinct-approval-one}

나무위키 [제21대 국회의원 선거/여론조사](https://namu.wiki/w/제21대 국회의원 선거/여론조사)에서 특정 여론조사를 선정하여 이를 긁어내어 데이터프레임으로 만들어보자.

```{r precinct-approval-data-webshot}
webshot2::webshot("https://namu.wiki/w/제21대 국회의원 선거/여론조사", selector = '#app > div > div:nth-child(2) > article > div:nth-child(5) > div:nth-child(2) > div > div > div:nth-child(49) > div:nth-child(20) > table', "data/one-sample.png")
```


전체 [제21대 국회의원 선거/여론조사](https://namu.wiki/w/제21대 국회의원 선거/여론조사)에서 특정 선거구 "인천광역시 계양구 갑"을 선정하여 데이터를 스크랩핑하여 데이터프레임으로 변환시킨다.

```{r precinct-approval-data-one, eval = FALSE}
library(tidyverse)
library(rvest)

Sys.setlocale("LC_ALL", "C")

namu_html <- read_html("https://namu.wiki/w/제21대 국회의원 선거/여론조사")

namu_txt <- naum_html %>% 
  html_nodes('div.wiki-table-wrap') %>% 
  .[300] %>% 
  html_nodes('div.wiki-paragraph') %>% 
  html_text()

Sys.setlocale("LC_ALL", "Korean")

## 여론조사 구성요소별로 분리
### 여론조사개요
survey_title <- namu_txt[1]

survey_overview <- str_split_fixed(survey_title, ",", n=3)

survey_main <- namu_txt[-1]

### 후보자 지지율
survey_value <- survey_main[str_detect(survey_main, "%")]

### 후보자 정당
survey_text <- survey_main[str_detect(survey_main, "^(?!.*%)")]

index_vec <- str_detect(survey_text, "무당층")

location_무당층 <- which(str_detect(survey_text, "무당층"))

survey_party <- survey_text[1:location_무당층]

### 후보자명
survey_candidate <- c(survey_text[(location_무당층+1):length(survey_text)], "무당층")


# 데이터프레임

one_sample_df <- tibble(정당 = survey_party,
      후보자명 = survey_candidate,
      지지율 = survey_value,
      조사업체 = survey_overview[1],
      조사방식 = survey_overview[2],
      조사일자 = survey_overview[3])

one_sample_df %>% 
  write_rds("data/one_sample_df.rds")
```

제대로 스크랩핑이 되었는지 확인한다.

```{r precinct-approval-data-one-output}
one_sample_df <- read_rds("data/one_sample_df.rds")

one_sample_df %>% 
  DT::datatable()
```

