---
layout: page
title: "재보선 2019 선거"
subtitle: "각종 여론조사"
author:
    name: xwMOOC
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 대통령 지지율 {#president-approval}

- 데이터 출처: [위키백과: 대한민국의 대통령 지지율](https://ko.wikipedia.org/wiki/대한민국의_대통령_지지율)
- 조사기관
    - [리얼미터(Real Meter)](http://www.realmeter.net/)
    - [갤럽(Gallop)](http://www.gallup.co.kr/)

# 여론조사 데이터 [^unicode-converter] {#namu-survey-data}

[^unicode-converter]: [Unicode Converter - Decimal, text, URL, and unicode converter](https://www.branah.com/unicode-converter)

```{r survey-president-approval}
library(tidyverse)
library(rvest)
library(lubridate)

namu_url <- "https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EB%8C%80%ED%86%B5%EB%A0%B9_%EC%A7%80%EC%A7%80%EC%9C%A8"

Sys.setlocale("LC_ALL", "C")

moon_dat <- namu_url %>% 
  read_html() %>% 
  html_nodes(xpath='//*[@id="mw-content-text"]/div/table') %>%
  html_table(fill=TRUE) %>% 
  .[[1]]
Sys.setlocale("LC_ALL", "Korean")

moon_part_one_df <- moon_dat %>%
  set_names(c("날짜1", "갤럽1", "리얼미터1", "날짜2", "갤럽2", "리얼미터2")) %>% 
  select(`날짜1`, `갤럽1`, `리얼미터1`) %>% 
  filter(! row_number() %in% c(1,2,3)) %>% 
  rename(`날짜` = `날짜1`,
         `갤럽` = `갤럽1`,
         `리얼미터` = `리얼미터1`) %>% 
  mutate(`갤럽` = str_extract(`갤럽`, "^\\d.+\\.\\d") %>% as.numeric) %>% 
  mutate(`리얼미터` = str_extract(`리얼미터`, "^\\d.+\\.\\d") %>% as.numeric)

moon_part_two_df <- moon_dat %>%
  set_names(c("날짜1", "갤럽1", "리얼미터1", "날짜2", "갤럽2", "리얼미터2")) %>% 
  select(`날짜2`, `갤럽2`, `리얼미터2`) %>% 
    rename(`날짜` = `날짜2`,
           `갤럽` = `갤럽2`,
           `리얼미터` = `리얼미터2`) %>% 
  filter(! row_number() %in% c(1,2,3)) %>% 
  mutate(`갤럽` = str_extract(`갤럽`, "^\\d.+\\.\\d") %>% as.numeric) %>% 
  mutate(`리얼미터` = str_extract(`리얼미터`, "^\\d.+\\.\\d") %>% as.numeric) %>% 
  filter(!str_detect(`날짜`, "NA"))

moon_dat <- bind_rows(moon_part_one_df, moon_part_two_df) %>% 
  tbl_df

moon_dat <- moon_dat %>% 
  mutate(`연도` = str_extract(`날짜`, "^\\d{4}") %>% as.integer) %>% 
  mutate(`월`   = str_extract(`날짜`, "\\b\\d{1,2}월\\b") %>% str_remove(., "월") %>% as.integer) %>% 
  mutate(`주`   = str_extract(`날짜`, "\\b((?!주)\\d{1}주$)\\b") %>% str_remove(., "주") %>% as.integer) 
  

korean_week_df <- tibble(
  `조사날짜` = seq(ymd("2017-01-01"), ymd("2019-02-15"), 1)
) %>% 
  mutate(`주차` = week(`조사날짜`),
         `연도` = year(`조사날짜`),
         `월`   = month(`조사날짜`)) %>% 
  group_by(`연도`, `월`) %>% 
  mutate(`한국주` = `주차` - min(`주차`) +1 ) %>% 
  group_by(`연도`, `월`, `한국주`) %>% 
  summarise(`조사날짜` = min(`조사날짜`))

moon_df <- left_join(moon_dat, korean_week_df, by=c("연도" = "연도", "월"="월", "주"="한국주")) %>% 
  select(`날짜`, `조사날짜`, `갤럽`, `리얼미터`)

moon_df %>% write_csv("data/moon_df.csv")

```


```{r 대통령_지지율}
library(tidyverse)
library(extrafont)
loadfonts()

moon_df  <- read_csv("data/moon_df.csv")

moon_df %>% 
  select(-`날짜`) %>% 
  gather(`조사기관`, `지지율`, -`조사날짜`) %>% 
  ggplot(aes(x=`조사날짜`, y=`지지율`, color=`조사기관`)) +
    geom_line() +
    geom_point() +
    scale_x_date(date_labels = "%Y-%m") +
    theme_minimal(base_family = "NanumGothic") +
    scale_color_manual(values = c("gray30", "skyblue")) +
    labs(x="", y="지지율(%)", title="문재인 대통령 지지율") +
    theme(legend.position = "top")

moon_df %>% 
  arrange(desc(`조사날짜`)) %>% 
  DT::datatable()

```